name: HiFiNi 自动签到
 
on:
    workflow_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '12 2 * * *'   # 对应中国时间每天上午10:12运行一次

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v3
            - name: Set go
              uses: actions/setup-go@v3
              with:
                go-version: '^1.14'
            - name: HIFINI 自动签到
              env:
                COOKIE: ${{ secrets.COOKIE }}
              run: go run main.go
